module(
    name = "rules_lean",
    version = "0.0.1",
)

bazel_dep(name = "bazel_skylib", version = "1.5.0")
bazel_dep(name = "platforms", version = "1.0.0")

bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.1", dev_dependency = True)
bazel_dep(name = "rules_testing", version = "0.9.0", dev_dependency = True)

# Register mock toolchain for unit tests
register_toolchains(
    "//test/fixtures:mock_lean_toolchain",
    dev_dependency = True,
)
