module(
    name = "example_01_toolchain",
    version = "0.0.0",
)

bazel_dep(name = "rules_lean", version = "0.0.1")
local_path_override(
    module_name = "rules_lean",
    path = "../..",
)

lean = use_extension("@rules_lean//lean:extensions.bzl", "lean")
lean.toolchain(version = "4.12.0")
use_repo(lean, "lean_toolchain_linux_x86_64")

register_toolchains("@lean_toolchain_linux_x86_64//:lean_toolchain")
