"""Repository rule for parsing Lean imports and generating dependency information.

This is a proof-of-concept for using repository rules to solve the Lean dependency
ordering problem. Lean requires compiling imports before the importing module, but
Bazel requires the action graph to be declared at analysis time when imports aren't
known yet.

This repo rule:
1. Watches a source directory for changes (via watch_tree)
2. Parses all .lean files to extract import statements
3. Generates BUILD.bazel with dependency information
"""

def _find_lean_files(repository_ctx, path):
    """Recursively find all .lean files under a path."""
    result = repository_ctx.execute(["find", str(path), "-name", "*.lean", "-type", "f"])
    if result.return_code != 0:
        fail("Failed to find .lean files: " + result.stderr)

    files = []
    for line in result.stdout.strip().split("\n"):
        if line:
            files.append(line)
    return files

def _parse_imports(content):
    """Parse import statements from Lean source content.

    Lean import syntax:
        import Foo.Bar.Baz

    Returns a list of module names (e.g., ["Foo.Bar.Baz", "Other.Module"]).
    """
    imports = []
    for line in content.split("\n"):
        line = line.strip()
        if line.startswith("import "):
            # Extract module name after "import "
            module = line[7:].strip()
            # Handle comments on same line
            if "--" in module:
                module = module[:module.index("--")].strip()
            if module:
                imports.append(module)
    return imports

def _module_name_from_path(file_path, src_dir):
    """Convert a file path to a Lean module name.

    Args:
        file_path: Path like "/workspace/src/Foo/Bar.lean"
        src_dir: Source directory like "/workspace/src"

    Returns:
        Module name like "Foo.Bar"
    """
    # Get relative path from src_dir
    if file_path.startswith(src_dir):
        rel_path = file_path[len(src_dir):]
        if rel_path.startswith("/"):
            rel_path = rel_path[1:]
    else:
        rel_path = file_path

    # Remove .lean extension and convert / to .
    if rel_path.endswith(".lean"):
        rel_path = rel_path[:-5]

    return rel_path.replace("/", ".")

def _path_from_module_name(module_name):
    """Convert a module name to a relative file path.

    Args:
        module_name: Module name like "Foo.Bar"

    Returns:
        Relative path like "Foo/Bar.lean"
    """
    return module_name.replace(".", "/") + ".lean"

def _topological_sort(dep_graph):
    """Topologically sort modules based on their dependencies.

    Args:
        dep_graph: Dict of module_name -> [list of imported modules]

    Returns:
        List of module names in compilation order (dependencies first).
    """
    # Build reverse graph for in-degree calculation
    in_degree = {m: 0 for m in dep_graph}
    for module, deps in dep_graph.items():
        for dep in deps:
            if dep in in_degree:
                in_degree[module] = in_degree.get(module, 0)

    # Calculate actual in-degrees
    for module, deps in dep_graph.items():
        for dep in deps:
            if dep in dep_graph:  # Only count internal dependencies
                in_degree[module] = in_degree.get(module, 0) + 1

    # Kahn's algorithm
    queue = [m for m, d in in_degree.items() if d == 0]
    result = []

    while queue:
        # Sort for deterministic output
        queue.sort()
        module = queue.pop(0)
        result.append(module)

        # Reduce in-degree for dependents
        for other_module, deps in dep_graph.items():
            if module in deps and other_module in in_degree:
                in_degree[other_module] -= 1
                if in_degree[other_module] == 0:
                    queue.append(other_module)

    # Check for cycles
    if len(result) != len(dep_graph):
        remaining = [m for m in dep_graph if m not in result]
        fail("Cycle detected in imports. Remaining modules: " + str(remaining))

    return result

def _generate_build_file(dep_graph, compilation_order, src_dir_rel):
    """Generate BUILD.bazel content with dependency information.

    Args:
        dep_graph: Dict of module_name -> [list of imported modules]
        compilation_order: List of modules in topological order
        src_dir_rel: Relative path to source directory from workspace root

    Returns:
        BUILD.bazel content as a string.
    """
    lines = [
        '"""Generated BUILD file with Lean dependency information.',
        '',
        'This file was auto-generated by lean_deps repository rule.',
        'DO NOT EDIT MANUALLY.',
        '"""',
        '',
        'load("@rules_lean//lean:defs.bzl", "lean_binary")',
        '',
        '# Dependency graph (module -> dependencies):',
    ]

    for module in compilation_order:
        deps = dep_graph.get(module, [])
        internal_deps = [d for d in deps if d in dep_graph]
        lines.append('#   {} -> {}'.format(module, internal_deps))

    lines.append('')
    lines.append('# Compilation order (dependencies first):')
    lines.append('# ' + ' -> '.join(compilation_order))
    lines.append('')
    lines.append('# Modules as a list for programmatic access')
    lines.append('LEAN_MODULES = [')
    for module in compilation_order:
        lines.append('    "{}",'.format(module))
    lines.append(']')
    lines.append('')

    lines.append('# Dependency graph as a dict')
    lines.append('LEAN_DEPS = {')
    for module in compilation_order:
        deps = dep_graph.get(module, [])
        internal_deps = [d for d in deps if d in dep_graph]
        lines.append('    "{}": {},'.format(module, internal_deps))
    lines.append('}')
    lines.append('')

    lines.append('# Source file paths (relative to workspace root)')
    lines.append('LEAN_SOURCES = {')
    for module in compilation_order:
        src_path = src_dir_rel + "/" + _path_from_module_name(module)
        lines.append('    "{}": "{}",'.format(module, src_path))
    lines.append('}')
    lines.append('')

    # Generate filegroup for all sources
    lines.append('filegroup(')
    lines.append('    name = "all_sources",')
    lines.append('    srcs = [')
    for module in compilation_order:
        src_path = src_dir_rel + "/" + _path_from_module_name(module)
        lines.append('        "@//{}",'.format(src_path))
    lines.append('    ],')
    lines.append('    visibility = ["//visibility:public"],')
    lines.append(')')
    lines.append('')

    return '\n'.join(lines)

def _lean_deps_impl(repository_ctx):
    """Implementation of lean_deps repository rule."""

    # Get the workspace root and source directory
    workspace_root = repository_ctx.workspace_root
    src_dir_rel = repository_ctx.attr.src_dir
    src_dir = workspace_root.get_child(src_dir_rel)

    # Watch the source directory for changes
    # Any modification to .lean files will trigger re-evaluation
    repository_ctx.watch_tree(src_dir)

    # Find all .lean files
    lean_files = _find_lean_files(repository_ctx, src_dir)

    if not lean_files:
        # No Lean files found, create empty BUILD
        repository_ctx.file("BUILD.bazel", """
# No Lean files found in {}
LEAN_MODULES = []
LEAN_DEPS = {{}}
LEAN_SOURCES = {{}}
""".format(src_dir_rel))
        return

    # Parse imports from each file and build dependency graph
    dep_graph = {}
    src_dir_str = str(src_dir)

    for file_path in lean_files:
        content = repository_ctx.read(file_path)
        module_name = _module_name_from_path(file_path, src_dir_str)
        imports = _parse_imports(content)
        dep_graph[module_name] = imports

    # Compute compilation order
    compilation_order = _topological_sort(dep_graph)

    # Generate BUILD.bazel
    build_content = _generate_build_file(dep_graph, compilation_order, src_dir_rel)
    repository_ctx.file("BUILD.bazel", build_content)

    # Also generate a .bzl file for loading the data
    bzl_content = '''"""Generated Lean dependency information.

This file was auto-generated by lean_deps repository rule.
DO NOT EDIT MANUALLY.
"""

# Modules in compilation order (dependencies first)
LEAN_MODULES = {}

# Dependency graph: module -> list of dependencies
LEAN_DEPS = {}

# Source paths: module -> workspace-relative path
LEAN_SOURCES = {}
'''.format(
        repr(compilation_order),
        repr({m: [d for d in dep_graph[m] if d in dep_graph] for m in compilation_order}),
        repr({m: src_dir_rel + "/" + _path_from_module_name(m) for m in compilation_order}),
    )
    repository_ctx.file("deps.bzl", bzl_content)

lean_deps = repository_rule(
    implementation = _lean_deps_impl,
    attrs = {
        "src_dir": attr.string(
            mandatory = True,
            doc = "Path to the source directory containing .lean files, relative to workspace root.",
        ),
    },
    doc = """Repository rule that parses Lean imports and generates dependency information.

This rule watches the specified source directory and re-evaluates whenever any
.lean file changes. It parses import statements to build a dependency graph
and outputs the compilation order.

Example:
    # In MODULE.bazel or WORKSPACE
    lean_deps(
        name = "my_lean_deps",
        src_dir = "src",
    )

    # Then in BUILD files, you can load the generated data:
    load("@my_lean_deps//:deps.bzl", "LEAN_MODULES", "LEAN_DEPS", "LEAN_SOURCES")
""",
)
