name: Test Lean Binary Rule
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: ./bazel test //test/...

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build hello world
        run: .github/workflows/test-lean-binary/step-2.1-build-hello-world.sh
      - name: Test exit code propagation
        run: .github/workflows/test-lean-binary/step-2.2-test-exit-code.sh
      - name: Test module naming
        run: .github/workflows/test-lean-binary/step-2.3-test-module-naming.sh
